# Deploy ELK
# http://elk-docker.readthedocs.io/
# https://hub.docker.com/r/sebp/elk/

version: '3.1'
services:
  nginx:
    image: custom-nginx:1.13.3
    hostname: nginx
    container_name: nginx
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
    command: [ 'sh', './bootstrap_nginx.sh' ]
  elk:
    image: sebp/elk:550
    hostname: elk
    container_name: elk
    ports:
    - "5601:5601/tcp"
    - "9200:9200/tcp"
    - "5044:5044/tcp"
    volumes:
    - esdata:/var/lib/elasticsearch

volumes:
  esdata:
    external: true
